version: '3.8'

services:
  #serviços backend(FastAPI)
  backend:
    build: ./backend
    container_name: backend-container
    ports:
      - "8000:8000"
    env_file:
      - .env

  #serviços frontend(Streamlit)
  frontend:
    build: ./frontend
    container_name: frontend-container
    ports:
      - "8501:8501"
    depends_on:
      - backend 
