"""Initial migration

Revision ID: e2718df24dbf
Revises: 
Create Date: 2026-07-23 18:29:03.721644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e2718df24dbf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Alterations to the recipe_ingredients table
    op.alter_column('recipe_ingredients', 'ingredient_name',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('recipe_ingredients', 'quantity',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    
    # Foreign key constraints for recipe_ingredients
    op.drop_constraint(op.f('recipe_ingredients_ibfk_1'), 'recipe_ingredients', type_='foreignkey')
    op.create_foreign_key(None, 'recipe_ingredients', 'recipes', ['recipe_id'], ['id'])
    
    # 2. Alterations to the recipes table
    op.alter_column('recipes', 'instructions',
               existing_type=mysql.TEXT(),
               nullable=True)
    
    # Drop the old constraint from recipes BEFORE altering the column to prevent error 1830
    op.drop_constraint(op.f('recipes_ibfk_1'), 'recipes', type_='foreignkey')
    
    op.alter_column('recipes', 'category_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    
    # Create the new updated foreign key constraint
    op.create_foreign_key(None, 'recipes', 'categories', ['category_id'], ['id'])
    
    # Drop the old unnecessary column
    op.drop_column('recipes', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False))
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.create_foreign_key(op.f('recipes_ibfk_1'), 'recipes', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_recipes_id'), table_name='recipes')
    op.alter_column('recipes', 'category_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('recipes', 'instructions',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.drop_constraint(None, 'recipe_ingredients', type_='foreignkey')
    op.create_foreign_key(op.f('recipe_ingredients_ibfk_1'), 'recipe_ingredients', 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_recipe_ingredients_id'), table_name='recipe_ingredients')
    op.alter_column('recipe_ingredients', 'quantity',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('recipe_ingredients', 'ingredient_name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    # ### end Alembic commands ###
